name: First GitHub Action

on: 
  push:
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Print Hello Message
        run: echo "Hello, GitHub Actions!"
